version: '3.8'

volumes:
  data: {}

services:
  app:
    image: kennethkl/sshauth:${VERSION:-latest}
    build:
      context: .
      args:
        VERSION: ${VERSION:-latest}
    environment:
      - APP_ENV=production

      # Header auth options. Do not set if you don't want to use header auth
      - HEADER_AUTH_EMAIL # Email header
      - HEADER_AUTH_NAME  # Name header
      - HEADER_AUTH_USERNAME # Username header
      - AUTO_CREATE_USER  # Create user if not exists
    volumes:
      - data:/app/pb_data
